### ISSUE TITLE
Not an issue ;-)

### ISSUE THREAD

**Issue by bradparks** [jrdoughty/Kha-examples#1]
Hey! thanks for the samples.... I'm new to Kha, and just tried to run these, and they all ran great... Thanks for taking the time to post them....

I actually was about to write an issue on how to run them, but got Kode Studio, and figured out how to load a sample, and then it was easy...

But if you really want someone to try your samples, especially if they're 100% new to Kha, I think having a bit more info on how to get going would be great.

For example:
- Get Kode Studio from here: https://github.com/KTXSoftware/KodeStudio/releases
- After it's installed, run "File | Open", and browse for one of the samples, say "Tetris".
- Press F5 to run the project.

I know - not alot of info, but I wasn't 100% sure how to run them, especially since I didn't see Kha installed when I git cloned it recursively.

Once again - thanks a ton for your samples... Very nice!

Brad

**Comment by jrdoughty** [comment]
Glad you liked them! Hopefully I'll be able to add some more here soon. I think you make a good point, and I think I can make this repo much better by linking to a few other resources. I'll make a few alterations to the read me shortly. 

Thank you for the feedback!

**Comment by bradparks** [comment]
Thanks! Great work!
